#!/bin/bash

read -p "Validate Date: " date1 date2

pat="^[0-9]{8}$"

if [[ $date1 =~ $pat ]] && [[ $date2 =~ $pat ]]; then
    echo "$date1 and $date2 are valid"
else
    echo "$date1 or $date2 is invalid"
fi

read -sp "Enter the secret code: " secret

if [ "$secret" == "password" ]; then
    echo " Please enter"
else
    echo " Wrong Password!"
fi
