#!/bin/bash

while read avg rbis hrs; do
    printf "Avg: ${avg}\nRBIs: ${rbis}\nHRs: ${hrs}\n"

done < iulian.stats


for (( i=0; i <= 10; i++ )); do
    echo $i
done


for i in {A..Z}; do
    echo $i
done


