#!/bin/bash

#arrays
fav_nums=(3.14 2.718 .22 3.2)

echo "Pi: ${fav_nums[0]}"

# add to array 2 aditional elements

fav_nums+=(1 7)
for i in ${fav_nums[*]}; do
    echo $i
done


# print index values
fav_nums+=(1 7)
for i in ${fav_nums[@]}; do
    echo $i
done

echo "Array Length: ${#fav_nums[@]} "

echo "Index 3 Length: ${#fav_nums[3]}"

sorted_nums=($(for i in "${fav_nums[@]}"; do 
    echo $i;
done | sort))

echo "Sorted:"

for i in ${sorted_nums[@]}; do
    echo $i
done

unset 'sorted_nums[1]'
unset sorted_nums


